name: errflow
description: A package for making it somewhat easier to comprehend the flow of errors and handle them.
version: 0.4.0-nullsafety.2
homepage: https://github.com/kaboc/dart_errflow

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"

dependencies:
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  test: ^1.16.0-nullsafety.17
