name: errflow
description: A Dart package for easier and more comprehensible flow of error handling and logging.
version: 0.5.0
repository: https://github.com/kaboc/dart_errflow

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.4
