name: errflow
description: A package for making it somewhat easier to comprehend the flow of errors and handle them.
version: 0.1.2
homepage: https://github.com/kaboc/dart_errflow

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  test: ^1.15.1
