name: errflow
description: A Dart package for easier and more comprehensible flow of error handling and logging.
version: 0.4.1
repository: https://github.com/kaboc/dart_errflow

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.19.3
